### PR TITLE
BGDIINF_SB-2380: Added ADR for short ID algorithm

### PR DESCRIPTION
**Pull request by ltshb**

### CODE REVIEW

**Review by rebert — APPROVED** [review]
I agree with the conclusion. Thanks for the summation.

**Review by hansmannj — APPROVED** [review]
Thanks for the effort here @ltshb :+1:

I tried to verify the calculated collision risk using a different approximation and got (almost) the same results as you did :wink:

```python
def approximation(n, d):
    p = 1 - math.exp(-1*n**2 / (2*d))
    return p
```

Also double checked with the numbers in the birthday paradoxon that you referred to: https://en.wikipedia.org/wiki/Birthday_problem.

Unexpected after a first glimpse, that we get a 99% collision risk after 10 years although we'd have only a very small fraction of all available combinations in use so far. Guess that's why it's called paradoxon :wink:

I agree with the suggested decision. Keeping our current algorithm is fine. And even if we get 1 or 2 more characters after 2037  is not a big deal from my point of view.

**Comment by fkm** [comment]
Keeping the same algorithm sounds sane.

But I would recommend against using the BGDI domain. Most people don't know that this is related to admin.ch and might be reluctant to open it.

**Review by procrastinatio — APPROVED** [review]
The two main applications of the shorturl were **twitter** (limited to less thant 160 characters back then ) and the **QRcode** (using shorturls, otherwise the image is unreadable). It's nice to keep short, but that all (when was the last time you wrote a shorturl in the URL bar?)
And frankly, what happen past 2030, is not my business anymore.

**Comment by davidoesch** [comment]
- additional application of shorturl: to be used as link  in text: mail , documentation etc 
- domain: s.geo.admin.ch is a must ( BGDI.CH is internal use only, admin.ch is a domin of trust.) there were once plans to have a short URL provided by admin.ch --so we might have solved this in the future /2037
-  lenght: Max 10 char: since otherwise the QR code might become unreadable on prints (to small)

**Pull request merged**
